### PR TITLE
Feature/boston2018

### PR DESCRIPTION
**Pull request by timosachsenberg**
merge boston changes into master

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I think we can then put the changes for the current 2.4 release on top? what do you think?

**Comment by timosachsenberg** [comment]
e.g.:

- KNIME 3.6
- branch on update site

**Comment by oliveralka** [comment]
Metabolomics:
update: Fig 30, 32, 33
add: MS2 de-novo identification using SiriusAdapter (input mzML and featureXML)
(SiriusAdapter and MetaboliteAdductDecharger for Feature Adduct information)

Is there a paragraph for the MetaboliteAdductDecharger and its usage? @FabianAicheler

**Comment by timosachsenberg** [comment]
- do we need to update the R version in the handout?

**Pull request merged**
