### PR TITLE
Draft for MSstats iPRG tutorial

### PR DESCRIPTION
**Pull request by oliveralka**
Add draft for Integration of iPRG MSstats Tutorial.

Missing:
- [x] 1. Short excursion on MSstats (what is it, what kind of functions and so on).
- [x] 2. Explanation of the background (iPRG - data) 
- [x] 3. Citation IPRG (https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.6b00881)
- [x] 4. Further explanation of the experimental design 
- [x] 6. Fig: complete workflow 
- [x] 7. Fig: extract (conversion + downstream analysis for tutorial) 
- [x] 8. Fig: analysis plots
- [ ] 9. Explanation where to find the data and how to use it
- [ ] 10. Short interpretation of the analysis
- [ ] 13. Layout & expression

Please let me know if you have other ideas or suggestion and if we should divide the work somewhat.

A lot of work has already be done by @lukaszimmermann and just needs some "pretty up" for the tutorial handout.

### CODE REVIEW

**Comment by oliveralka** [comment]
@mrurik @lukaszimmermann Are you able to help with that?

**Comment by jpfeuffer** [comment]
Dowe really want the whole Tutorial? With pyopenms and OpenSwath? @timosachsenberg

**Comment by timosachsenberg** [comment]
no and I think I disabled them https://github.com/OpenMS/Tutorials/blob/feature/Boston2018/Handout/handout.tex#L261

**Comment by jpfeuffer** [comment]
sorry, right, pdf was not uptodate. I previewed too early.

**Comment by jpfeuffer** [comment]
@oliveralka Why is there a double line in the Table of spike ins? Special meaning?

**Comment by jpfeuffer** [comment]
Still the MSStats conversion, KNIME R workflow missing.
I can't do it because of the KNIME bug.

**Comment by jpfeuffer** [comment]
WE have to decide on the structure on the USB stick to fix folder and workflow names/paths.

**Comment by lukaszimmermann** [comment]
Couldn't add them. Have to check.

**Comment by lukaszimmermann** [comment]
Thanks, this was the problem.

**Pull request merged**
