### PR TITLE
Update handout with ThermoRawFileParser

### PR DESCRIPTION
**Pull request by Leon-Bichmann**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
I dont think we include the compiled PDF. It will be generated by Jenkins and uploaded.
But it does not compile. Maybe the underscores in the \ref?

**Comment by jpfeuffer** [comment]
Sorry, it DID compile but our SSH server is currently down.

**Comment by Leon-Bichmann** [comment]
ok I see, yeah it compiled for me as well.

**Comment by Leon-Bichmann** [comment]
Should we just merge it? Or retrigger jenkins?

**Comment by oliveralka** [comment]
Should we add that to the release/2.6.0 branch?

**Comment by Leon-Bichmann** [comment]
ah yes sure

**Pull request merged**
