### PR TITLE
[ADD] MAD 

### PR DESCRIPTION
**Pull request by oliveralka**
Add metabolomics Metabolite Adduct Decharger
Fix _de novo_ identification

### CODE REVIEW

**Comment by FabianAicheler** [comment]
Fine with me (^^), I'll add the new workflow as a separate pull request

**Comment by oliveralka** [comment]
@FabianAicheler It seems there is a small error in the picture (MetaboliteAdductDecharger 2x),
Please fix.

**Comment by FabianAicheler** [comment]
What error? 

(MetaboliteAdductDecharger is supposed to be chained for this example)

**Comment by oliveralka** [comment]
Ok, thank you!

**Pull request merged**
