### PR TITLE
OpenMS 2.7: Update WF related to Sirius

### PR DESCRIPTION
**Pull request by oliveralka**
Update Tutorials related to SIRIUS upgrade for OpenMS 2.7 release.

TODOs:
- [x] Update and test DIAMetAlyzer.knwf
- [x] Update documentation also related to #186
- [x] Further correct .tex if necessary e.g. internal decoy generation since SIRIUS 4.5, feature linking included in AGM (depending on parameterization more stringent, since it uses only feature with identification information (known) - point to occurrence filter. 
- [x] Change KNIME workflow figure to new workflow structure (without python node in the middle)!

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@oliveralka ping because of conflicts. We e.g. use a new package for code snippets for HTML documentation.

**Comment by jpfeuffer** [comment]
The workflow is KNiME 4.4 and OpenMS 2.7 ready?

**Comment by oliveralka** [comment]
> The workflow is KNiME 4.4 and OpenMS 2.7 ready?

Yes, the workflow is KNIME 4.4.0 and OpenMS 2.7 ready!

**Comment by jpfeuffer** [comment]
Ok feel free to merge. Hmm didnt we have CI for this repo?

**Comment by oliveralka** [comment]
Does not seem so - guess we have to check if the handout is compiling then. 
I currently have some problems with minted env on macOS.

**Comment by jpfeuffer** [comment]
you need pygments tool

**Comment by jpfeuffer** [comment]
I'll try to update the README. I thought I did already.

**Pull request merged**
