### PR TITLE
[UPDATE] First changes EuBIC2019

### PR DESCRIPTION
**Pull request by oliveralka**
First changes to OpenSWATH and pyOpenMS.

Will push more to this PR in the following days.

### CODE REVIEW

**Comment by oliveralka** [comment]
@hroest @timosachsenberg I think most of the OpenSWATH and pyOpenMS layout is finished. Please have a look. I still have some problems with the old CLI commands for OpenSWATH (will figure this out). 
We will have to take a look at getting started (Installers, urls, KNIME, etc.).

**Comment by oliveralka** [comment]
Missing: standalone script for mProphet

Fixed: TargetedFileConverter, OpenSwathDecoyGenerator commands 
Edit: smaller changes (language/style)
Add: further citations

**Comment by oliveralka** [comment]
Missing: Change mProphet to pyProphet (or add), since python has to be installed anyway to use pyOpenMS later on. 

edit: further changes in style and directory structure

@Leon-Bichmann May you have a short look on the pyOpenMS Part - if you like the examples or have other suggestions. We could add one/two short ones (before getting to the tool dev).

**Comment by Leon-Bichmann** [comment]
alright, Ill have a look

**Comment by Leon-Bichmann** [comment]
On the tutorial stick we provide a pyopenms.whl file for installation without internet.
Maybe we should include a sentence that you can install it like this:
pip install pyopenms.whl

However this is still downloading the package numpy from the internet, so we might need to ship this one as well:
``
Processing ./pyopenms-2.4.0-cp37-cp37m-macosx_10_7_x86_64.whl
Collecting numpy (from pyopenms==2.4.0)
  Downloading https://files.pythonhosted.org/packages/3d/c3/a69406093c9a780a74964f41cd56b06c0346d686a9b3f392d123a663f5e0/numpy-1.15.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
    100% |████████████████████████████████| 24.5MB 1.5MB/s 
Installing collected packages: numpy, pyopenms
Successfully installed numpy-1.15.4 pyopenms-2.4.0
``

**Comment by Leon-Bichmann** [comment]
still debugging, but im having some problems with the argparser script as well..

**Comment by oliveralka** [comment]
@Leon-Bichmann What is the problem?

**Comment by Leon-Bichmann** [comment]
So I was running in some errors there:

the 'dest' argument doesnt seem to work with my python version:

`  File "/Users/bichmann/anaconda3/envs/py37/lib/python3.7/argparse.py", line 1334, in add_argument
    raise ValueError('dest supplied twice for positional argument')`

**Comment by Leon-Bichmann** [comment]
> So I was running in some errors there:
> 
> the 'dest' argument doesnt seem to work with my python version:
> 
> ` File "/Users/bichmann/anaconda3/envs/py37/lib/python3.7/argparse.py", line 1334, in add_argument raise ValueError('dest supplied twice for positional argument')`

ok, the problem disappeared seems like I had some syntax bug in my script

**Comment by oliveralka** [comment]
Will use mProphet for now - to get the Tutorial going - since I have problems to install/compile pyProphet on Windows 10 with python 3.7 and currently whls are not available.

```
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

  ----------------------------------------
  Failed building wheel for pyprophet
```

To install the Build Tools another 3 GB of space are needed. Anaconda 3 used for python 3 is already taking 2.2 GB - I think this is not feasible for Users.

**Comment by oliveralka** [comment]
@timosachsenberg 
Most commands in the OpenSwath part are working - but sometimes the path has to specified further. (e.g. mquest=OpenSwath_quant.tsv -> "E:\...\OpenSwath_quant.tsv)
That is ok, or?

**Comment by timosachsenberg** [comment]
so we need full paths and relative paths don't work? if so, we should write this in the handout

**Comment by jpfeuffer** [comment]
I remember the issue with the copying! But did not look for solutions since we rarely did pyopenms after that.

**Comment by oliveralka** [comment]
We use now external code snipped files (e.g. Snippets_pyOpenMS), where the code can be copied without any problems and used in spyder or the terminal. If anyone finds a better solution (please let me know.)

**Pull request merged**
