### PR TITLE
Identification / Quantification

### PR DESCRIPTION
**Pull request by oliveralka**
Workflows for
"OpenMS for open source analysis of mass spectrometric data"
https://doi.org/10.7287/peerj.preprints.27766v1

### CODE REVIEW

**Comment by timosachsenberg** [comment]
is this the tmt version oder lfq?

**Comment by oliveralka** [comment]
Is the LFQ Version - can add a TMT version as well, but I think the User has to switch the FFC with the IsobaricAnalyzer.

**Comment by timosachsenberg** [comment]
This would be cool to have it. Maybe then reduce the rt toelrance of IDMapper?

**Comment by timosachsenberg** [comment]
and also adapt the search parameters I guess

**Comment by oliveralka** [comment]
Theoretically, you need the correct correction matrix for your TMT chemicals as well - this has to be specified by the user!

**Comment by oliveralka** [comment]
@jpfeuffer Would this example be a correct relative path for the example?

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Data/latest/Example_Data/Labelfree/datasets/lfq_spikein_dilution_1.mzML

knime://LOCAL/latest/Example_Data/Labelfree/datasets/lfq_spikein_dilution_1.mzML

**Comment by jpfeuffer** [comment]
Almost. I usually start in the "latest" subdirectory, since we do not really use the other datasets in the Tutorials yet. But this would be debatable and might change in the future.

**Comment by timosachsenberg** [comment]
saved this in a separate branch

**Pull request closed without merging**
